-- Seed data generated from index.html catalog. Regenerate, do not hand-edit.
INSERT INTO categories (id, name, emoji, sort_order) VALUES (1, 'Mjólk', '🥛', 1);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (1, 1, 'Mjólk', '🥛', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (1, 1, 'Bónda mjólk - 3,5% (1 L)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (2, 1, 'Millum mjólk - 1,5% (1 L)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (3, 1, 'Lætti mjólk - 0,5% (1 L)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (4, 1, 'Solti mjólk - 0,1% (1 L)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (5, 1, 'Haldfør mjólk (1 L)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (6, 1, 'Laktose frí mjólk (1 L)', 6, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (2, 'Súrróma & Róma', '🥣', 2);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (2, 2, 'Súrróma & Róma', '🥣', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (7, 2, 'Súrróma 18%', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (8, 2, 'Róma', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (9, 2, 'Róma matgerð', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (10, 2, 'Vaniljucreme', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (11, 2, 'Risifrutti Jarðber', 5, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (3, 'Jogurt', '🫙', 3);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (3, 3, 'Jogurt', '🫙', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (12, 3, 'Súrepli, Reyðrót & Lime (1 L)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (13, 3, 'Pera & Banan (1 L)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (14, 3, 'Jarðber (1 L)', 3, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (4, 'Egg', '🥚', 4);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (4, 4, 'Egg', '🥚', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (15, 4, '12 stk. Egg', 1, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (5, 'Smør & margarin', '🧈', 5);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (5, 5, 'Smør & margarin', '🧈', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (16, 5, 'Føroykst smør', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (17, 5, 'Kærgården', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (18, 5, 'Bakkendalen', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (19, 5, 'Vita 1', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (20, 5, 'Vita plantumagrin', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (21, 5, 'Rema 1000 plantemargarine', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (22, 5, 'Rema 1000 steikimargarine', 7, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (6, 'Breyð', '🍞', 6);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (6, 6, 'Breyð', '🍞', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (23, 6, 'Heil breyð', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (24, 6, '1/2 breyð', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (25, 6, 'Stórt formafransbreyð', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (26, 6, 'Lítil formafransbreyð', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (27, 6, 'Rund v/birkes', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (28, 6, 'Hagabreyð', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (29, 6, 'Hvidløgsflutes (Rema 1000)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (30, 6, 'Mini Flutes (Rema 1000, 750g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (31, 6, 'Fuldkorns Mini Flutes (Rema 1000, 400g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (32, 6, 'Morgenbrød (Rema 1000, 600g)', 10, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (7, 'Pålegg', '🥪', 7);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (7, 7, 'Pålegg', '🥪', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (33, 7, 'Makrel salat', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (34, 7, 'Livurpostei (Krás)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (35, 7, 'Krukku Livurpostei', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (36, 7, 'Speipilsa', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (37, 7, 'Skinku skivur', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (38, 7, 'Hamburgarrygg', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (39, 7, 'Rullipylsa (Krás)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (40, 7, 'Skinsakjøt (Krás)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (41, 7, 'Frokost Leverpostei (Stryhns)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (42, 7, 'Den Originale Salami (CBU, 125g)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (43, 7, 'Peber Spegepølsa (CBU, 125g)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (44, 7, 'Kylling Pølsa (CBU, 110g)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (45, 7, 'Hvidløgs Spegepølsa (CBU)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (46, 7, 'Frankfurter (Steff Houlberg, 450g)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (47, 7, 'Biksemad (Steff Houlberg)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (48, 7, 'Hamburgarbuffar (PH, 12 stk. / 600g)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (49, 7, 'Hamburgarryggur (PH, 100g)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (50, 7, 'Skinka (PH, 100g)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (51, 7, 'Jaka Bov (450g)', 19, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (8, 'Kjøt', '🥩', 8);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (8, 8, 'Kjøt', '🥩', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (52, 8, 'Bacon (Tulip, 200g)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (53, 8, 'Svínakotelettir (PH)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (54, 8, 'Svínakotelettir', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (55, 8, 'Hakkað oksakjøt (Jensen)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (56, 8, 'Hakkað kjøt (Skorðargarður)', 5, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (9, 'Fiskur', '🐟', 9);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (9, 9, 'Fiskur', '🐟', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (57, 9, 'Norðfra Fiskafrikadellur', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (58, 9, 'Norðfra Fiskavørur', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (59, 9, 'Turrur Fiskur (325g)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (60, 9, 'Rejer i lage (Rema 1000, 340g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (61, 9, 'Marineret sild (Fiskemandens, 600g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (62, 9, 'Kryddersild (Fiskemandens, 600g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (63, 9, 'Karrýsild (Fiskemandens, 500g)', 7, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (10, 'Eplir', '🥔', 10);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (10, 10, 'Eplir', '🥔', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (64, 10, 'Rómaeplir 2kg', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (65, 10, 'Eplir 2kg', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (66, 10, 'Eplir 5kg', 3, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (11, 'Kaffi', '☕', 11);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (11, 11, 'Kaffi', '☕', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (67, 11, 'Kaffi (Karat)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (68, 11, 'Kaffi (Givalia)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (69, 11, 'Merrild Specialristet (400g)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (70, 11, 'Merrild Gold (50g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (71, 11, 'Lavazza Qualità Oro (340g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (72, 11, 'Karat Instant (100g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (73, 11, 'Nescafé Gold (100g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (74, 11, 'Nescafé Gold Cappuccino (100g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (75, 11, 'Kaffefiltre (Rema 1000, 200 stk.)', 9, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (12, 'Te', '🫖', 12);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (12, 12, 'Te', '🫖', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (76, 12, 'Pickwick Jarðber (20 posar)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (77, 12, 'Pickwick Mango (20 posar)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (78, 12, 'Pickwick Variation Box (20 posar)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (79, 12, 'Pickwick Black Tea Variation (20 posar)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (80, 12, 'Pickwick Lemon (20 posar)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (81, 12, 'Pickwick Forest Fruit (20 posar)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (82, 12, 'Typhoo (80 posar)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (83, 12, 'Tetley Original (120 posar)', 8, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (13, 'Baking & Matur', '🧂', 13);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (13, 13, 'Baking & Matur', '🧂', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (84, 13, 'Dansk Sukker (Dan Sukker, 2kg)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (85, 13, 'Mjøl (Rema 1000) (2kg)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (86, 13, 'Mjøl (Amo) (2kg)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (87, 13, 'Brunfarin (Dan Sukker, 500g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (88, 13, 'Flormelis (Dan Sukker, 500g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (89, 13, 'Sukur terningar', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (90, 13, 'Rasp olja', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (91, 13, 'Kakao pulvur', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (92, 13, 'Cadbury Cocoa (125g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (93, 13, 'Lagereddike (Rema 1000, 1L)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (94, 13, 'Clemente Olivenolja (250ml)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (95, 13, 'Grahamsmel (Rema 1000, 1kg)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (96, 13, 'Rugmel (Rema 1000, 1kg)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (97, 13, 'JOZO Fint Salt med Jod (1kg)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (98, 13, 'JOZO Kokkesalt med Jod (800g)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (99, 13, 'Coffee Creamer (Rema 1000)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (100, 13, 'ReaLemon (Polenghi)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (101, 13, 'Bakegær (Malteserkors, 50g)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (102, 13, 'Lasagnette Blanding (Rema 1000, 280g)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (103, 13, 'Dates Pitted (400g)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (104, 13, 'Rosiner (Sun-Maid, 250g)', 21, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (105, 13, 'Rosiner (Rema 1000, 250g)', 22, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (106, 13, 'Svesker uden sten (Rema 1000, 200g)', 23, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (107, 13, 'Lys Sirup (Dan Sukker, 750g)', 24, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (108, 13, 'Golden Syrup (Lyle''s)', 25, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (109, 13, 'Budding Vaniljesmag (Dr. Oetker, 2-pak)', 26, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (110, 13, 'Rabarbergrød (Dr. Oetker)', 27, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (111, 13, 'Frugtgrød (Dr. Oetker)', 28, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (112, 13, 'Kagecreme Vaniljesmag (Dr. Oetker, 3 breve)', 29, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (113, 13, 'Gelé Jarðber (Freia)', 30, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (114, 13, 'Kakao (Jakobs)', 31, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (115, 13, 'Nugatti (Lynge Line)', 32, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (14, 'Sausar & Dressing', '🥫', 14);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (14, 14, 'Sausar & Dressing', '🥫', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (116, 14, 'Bähncke Tomatketchup (420g)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (117, 14, 'Bähncke Fransk Sennep', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (118, 14, 'French Dog Dressing (Bähncke)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (119, 14, 'Remoulade Den Originale (Graasten)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (120, 14, 'Thousand Island Dressing (Graasten, 425g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (121, 14, 'Coleslaw Dressing (Rema 1000, 416g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (122, 14, 'Hvidløgs Dressing (Rema 1000, 420g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (123, 14, 'Tomat Ketchup (Rema 1000, 500g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (124, 14, 'Dild Dressing (Rema 1000, 300g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (125, 14, 'Klassisk Remoulade (K-Salat, 375g)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (126, 14, 'Klassisk Mayonnaise (K-Salat, 375g)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (127, 14, 'Pasta Sauce (Rema 1000, 400g)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (128, 14, 'Mad Kulør (Rema 1000, 200ml)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (129, 14, 'Bearnaise Sauce (Knorr)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (130, 14, 'Hollandaise Sauce (Knorr, 3x3dl)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (131, 14, 'Green Pepper Sauce (Knorr)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (132, 14, 'Kartoffelmos (Knorr, 3 poser)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (133, 14, 'Peppersaus (Toro)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (134, 14, 'Kjøttkakesaus (Toro)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (135, 14, 'Brun Saus med Løk (Toro)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (136, 14, 'Brun Saus (Toro)', 21, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (137, 14, 'Hvit Saus (Toro)', 22, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (138, 14, 'Karrisós (Toro)', 23, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (15, 'Kryddarí', '🌶️', 15);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (15, 15, 'Kryddarí', '🌶️', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (139, 15, 'Cayennepeppar (Santa Maria)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (140, 15, 'Løgpulver (Santa Maria)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (141, 15, 'Pommes Friteskrydder (Santa Maria)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (142, 15, 'Ingefær (Santa Maria)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (143, 15, 'Svartpeppar (Santa Maria)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (144, 15, 'Nejlika (Santa Maria)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (145, 15, 'Kanel (Santa Maria)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (146, 15, 'Curry (Santa Maria)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (147, 15, 'Kryddpeppar Allehånde (Santa Maria)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (148, 15, 'Kød & Grill (Knorr)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (149, 15, 'Aromat (Knorr)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (150, 15, 'Taco Spice Mix Original (Santa Maria)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (151, 15, 'Beef Stock Cubes (OXO, 12 stk.)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (152, 15, 'Kjøttbuljong / Oksebuljong (Knorr, 10x)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (153, 15, 'Grønnsaksbuljong (Knorr, 10x)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (154, 15, 'Hønsebuljong (Knorr, 10x)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (155, 15, 'Fiskebuljong (Knorr, 6x)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (156, 15, 'Kardemomme Ekstrakt (Fuerte)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (157, 15, 'Przyprawa (Maggi)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (158, 15, 'Ristede Løg (Rema 1000)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (159, 15, 'Rasp (Rema 1000, 500g)', 21, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (16, 'Pasta & Wraps', '🍝', 16);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (16, 16, 'Pasta & Wraps', '🍝', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (160, 16, 'Skrúvir', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (161, 16, 'Tex Mex Tortillas (Rema 1000, 6 stk)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (162, 16, 'Suppehorn (Rema 1000, 500g)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (163, 16, 'Pasta Skruer (Rema 1000, 500g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (164, 16, 'Spaghetti (Rema 1000, 1kg)', 5, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (17, 'Nudlur', '🍜', 17);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (17, 17, 'Nudlur', '🍜', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (165, 17, 'Mr. Lee (Kylling)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (166, 17, 'Mr. Lee (Búff)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (167, 17, 'Mr. Lee í kopp (Kylling)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (168, 17, 'Mr. Lee í kopp (Búff)', 4, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (18, 'Rís', '🍚', 18);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (18, 18, 'Rís', '🍚', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (169, 18, 'Parboiled Ris (Rema 1000, 1kg)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (170, 18, 'Parboiled Ris í kokipose (Rema 1000, 500g)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (171, 18, 'Rundkornede Grødris (Rema 1000, 1kg)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (172, 18, 'Grødris (Pama, 450g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (173, 18, 'Ris í kokipose (Ben''s Original)', 5, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (19, 'Keks & Kaka', '🍰', 19);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (19, 19, 'Keks & Kaka', '🍰', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (174, 19, 'Hálvmáni Sitrón', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (175, 19, 'Hálvmáni (Marmor)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (176, 19, 'Sandkaka', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (177, 19, 'Marmor kaka', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (178, 19, 'Viscount (200g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (179, 19, 'Wagon Wheels (216g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (180, 19, 'Tofypops (120g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (181, 19, 'Tofypops Karamel (120g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (182, 19, 'Merba Fully Coated Cookies (175g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (183, 19, 'Merba Triple Chocolate Cookies (180g)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (184, 19, 'Merba Chocolate Cookies (150g)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (185, 19, 'Cadbury Dairy Milk Fingers (114g)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (186, 19, 'Tunnock''s Tea Cakes (6 stk. / 144g)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (187, 19, 'Homeblest (300g)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (188, 19, 'McVitie''s Digestives Karamel (250g)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (189, 19, 'Viscount Mint (200g)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (190, 19, 'Blandede Småkager (Rema 1000)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (191, 19, 'Jatten Vaniljsmak', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (192, 19, 'Göteborg''s Kex', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (193, 19, 'Table Water Large (Carr''s)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (194, 19, 'Kaptajn Kjeks (Sæir, 200g)', 21, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (20, 'Morgunmatur', '🥣', 20);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (20, 20, 'Morgunmatur', '🥣', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (195, 20, 'Cornflakes', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (196, 20, 'Rice crisps', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (197, 20, 'Chocko pops', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (198, 20, 'Músli (sjokuláta)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (199, 20, 'Músli', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (200, 20, 'Finvalsede Havregryn (Rema 1000)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (201, 20, 'Choko Mysli (Rema 1000, 750g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (202, 20, 'Frugt Mysli (Rema 1000, 1kg)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (203, 20, 'Granola Nødder (Rema 1000, 500g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (204, 20, 'Granola Chokolade (Rema 1000, 500g)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (205, 20, 'Cocoa Balls', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (206, 20, 'Corn Flakes (Rema 1000, 750g)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (207, 20, 'Rice Krispies (Kellogg''s)', 13, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (21, 'Sodavatn & Saft', '🥤', 21);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (21, 21, 'Sodavatn & Saft', '🥤', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (208, 21, 'Jolly (1,5L)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (209, 21, 'Jolly X (1,5L)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (210, 21, 'Jolly Time (1,5L)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (211, 21, 'Hindbær (1,5L)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (212, 21, 'Sisu (1,5L)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (213, 21, 'Sisu Null (1,5L)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (214, 21, 'Sport (1,5L)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (215, 21, 'Sisu Appelsin (1,5L)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (216, 21, 'Faxe Kondi (1,5L)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (217, 21, 'Faxe Kondi Lemon (1,5L)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (218, 21, 'Pepsi (0,5L)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (219, 21, 'Pepsi Max (0,5L)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (220, 21, 'Jolly (0,5L)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (221, 21, 'Ginger Ale', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (222, 21, 'Cider', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (223, 21, 'Lime', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (224, 21, 'Leitón Sitrón', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (225, 21, 'Capri-Sun Orange & Peach (330ml)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (226, 21, 'Capri-Sun Multivitamin (330ml)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (227, 21, 'Mist Æppel (250ml)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (228, 21, 'Mist Kola (250ml)', 21, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (229, 21, 'Mist (250ml)', 22, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (230, 21, 'Drív Grønt', 23, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (231, 21, 'Drív Appelsin', 24, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (232, 21, 'Aqua Citrus & Lime', 25, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (233, 21, 'Aqua Blóð Appelsin', 26, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (234, 21, 'Gatorade Cool Blue', 27, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (235, 21, 'Hindbær Limonada', 28, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (236, 21, 'Fjordfax Kakao (250ml)', 29, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (237, 21, 'Appelsin Hindbær saft (Rema 1000, 1L, sukkerfrí)', 30, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (238, 21, 'Hyldeblomst saft (Rema 1000, sukkerfrí)', 31, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (239, 21, 'Lesk Hindbær (1,5L)', 32, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (240, 21, 'Lesk Ananas (1,5L)', 33, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (241, 21, 'Sød Tranebærsaft (Rynkeby, 1+4)', 34, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (22, 'Húshaldsvørur', '🔋', 22);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (22, 22, 'Húshaldsvørur', '🔋', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (242, 22, 'Duracell AA (8 stk.)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (243, 22, 'Colgate Karies Kontrol (2 x 75ml)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (244, 22, 'Biotex Color', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (245, 22, 'Parfumefri Uld & Finvask (Rema 1000, 1L)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (246, 22, 'Toiletpapir (Rema 1000, 8 ruller)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (247, 22, 'Kompakt Køkkenrulle (Rema 1000)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (248, 22, 'Maxi Bleer 4 (Rema 1000, 7-16kg, 50 stk.)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (249, 22, 'Stor Vask med parfume (Rema 1000, 2,56kg)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (250, 22, 'Upp Vask Sitron (Kemilux, 780ml)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (251, 22, 'Upp Vask Rein (Kemilux, 750ml)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (252, 22, 'Opvask Citron (Rema 1000, 500ml)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (253, 22, 'Opvask Ultra Citron (Rema 1000, 500ml)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (254, 22, 'Vel Pure & Clear', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (255, 22, 'Palmolive', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (256, 22, 'Håndsæbe (Rema 1000, 500ml)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (257, 22, 'Afspændingsmiddel (Rema 1000, 500ml)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (258, 22, 'Alufolie (Rema 1000, 40m)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (259, 22, 'Husholdningsfilm (Rema 1000)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (260, 22, 'Bagepapir Rulle (Rema 1000)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (261, 22, 'Bagepapir Ark (Rema 1000, 20 stk.)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (262, 22, 'Alt Mulig Klude (Rema 1000)', 21, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (263, 22, 'Baby Skumvaskeklude (Rema 1000, 50 stk.)', 22, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (264, 22, 'Skuresvampe (Rema 1000, 10 stk.)', 23, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (265, 22, 'Vådservietter (Rema 1000, 100 stk.)', 24, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (266, 22, 'Trusse Indlæg Normal (Rema 1000, 45 stk.)', 25, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (267, 22, 'Bind Normal (Rema 1000)', 26, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (268, 22, 'Brun Sæbe (Rema 1000, 1L)', 27, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (269, 22, 'Neutral Skyllemiddel', 28, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (270, 22, 'Ajax Lemon', 29, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (271, 22, 'Bamseline Blid og Blød', 30, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (272, 22, 'Bamseline Fresh Lavendel', 31, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (273, 22, 'Parfumeri Kulørt (Rema 1000, 1kg)', 32, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (274, 22, 'Gróður Reins utan klór (Kemilux, 2,5L)', 33, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (275, 22, 'Gróður Reins (Kemilux, 2,5L)', 34, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (276, 22, 'Original Afløbsrens (Borup)', 35, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (277, 22, 'S1 Extra (Kemilux, 1L)', 36, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (278, 22, 'Sprinklara løgur (Kemilux, 2,5L)', 37, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (279, 22, 'Dekk Vask (Kemilux)', 38, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (280, 22, 'Klorin Original', 39, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (281, 22, 'Denatureret Sprit 93% (Borup)', 40, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (282, 22, 'Ethanol (Borup)', 41, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (283, 22, 'Autoshampoo (Procare, 1L)', 42, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (284, 22, 'Bilservietter (Dunlop, 40x)', 43, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (285, 22, 'Fryseposer med skrivefelt (Rema 1000, 8L, 50 stk.)', 44, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (286, 22, 'Fryseposer med skrivefelt (Rema 1000, 4L)', 45, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (287, 22, 'Kokiposar (Vestpack)', 46, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (288, 22, 'Frymiposar (Vestpack, 19L)', 47, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (289, 22, 'Rusksekkir (Malteserkross, 15L)', 48, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (23, 'Súltutoy', '🍓', 23);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (23, 23, 'Súltutoy', '🍓', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (290, 23, 'Blomsterhonning (Jakobsens, 425g)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (291, 23, 'Jarðberja Sultutoy', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (292, 23, 'Aprikós / Gularót Marmuláta', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (293, 23, 'Svisku Marmuláta', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (294, 23, 'Rabarbu Sultutoy', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (295, 23, 'Hindbær (Fynbo)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (296, 23, 'Jordbær Marmelade (Rema 1000, 500g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (297, 23, 'Jordbær Rabarber Marmelade (Rema 1000, 400g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (298, 23, 'Appelsin Marmelade (Rema 1000, 400g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (299, 23, 'Jarðberjamarmelaði (Rasmus Klump, 415g)', 10, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (24, 'Ostur', '🧀', 24);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (24, 24, 'Ostur', '🧀', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (300, 24, 'Danbo Mild & Cremet (Arla Klovborg)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (301, 24, 'Danbo Frisk & Kraftfuld (Arla Klovborg)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (302, 24, 'Burger cheese cheddar (President, 200g)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (303, 24, 'Ostur Feskur 45+ (Friskur)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (304, 24, 'Havarti 60+ (Arla)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (305, 24, 'RejeOst (Buko)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (306, 24, 'SkinkeOst (Buko)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (307, 24, 'Ananas ostur (Buko)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (308, 24, 'Naturel ostur (Buko)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (309, 24, 'Pikant ostur (Buko)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (310, 24, 'Mozzarella revet 45% (Arla Karolines Køkken)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (311, 24, 'Pizzatopping revet (Arla Karolines Køkken)', 12, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (25, 'Salatir', '🥗', 25);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (25, 25, 'Salatir', '🥗', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (312, 25, 'Kylling & baconsalat (K-Salat, 190g)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (313, 25, 'Russisk salat (K-Salat, 190g)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (314, 25, 'Æggesalat (K-Salat)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (315, 25, 'Frugtsalat (K-Salat, 150g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (316, 25, 'Hønsesalat (Rema 1000, 250g)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (317, 25, 'Makrelsalat (Rema 1000, 300g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (318, 25, 'Italiensk salat (Rema 1000, 300g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (319, 25, 'Finthakket Skinkesalat (Rema 1000, 250g)', 8, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (26, 'Dósamatur', '🥫', 26);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (26, 26, 'Dósamatur', '🥫', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (320, 26, 'Rødkål (Beauvais)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (321, 26, 'Herregårds Rødkål (Beauvais)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (322, 26, 'Rød Beder (Beauvais)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (323, 26, 'Klassisk Agurkesalat (Beauvais)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (324, 26, 'Drue Agurker (Sanso)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (325, 26, 'Søde Majs (Taste of Nature)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (326, 26, 'Hakkede Tomater (Rema 1000, 400g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (327, 26, 'Champignon i skiver (Taste of Nature)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (328, 26, 'Asparges Snitter i lage (Rema 1000, 420g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (329, 26, 'Erter & karotter (Bonduelle)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (330, 26, 'Erter og gulerødder (Noliko)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (331, 26, 'Hvide Bønner i tomatsauce (Noliko)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (332, 26, 'Heinz Beanz', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (333, 26, 'Kartofler (Rema 1000, 680g)', 14, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (27, 'Súpan & Gryta', '🍲', 27);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (27, 27, 'Súpan & Gryta', '🍲', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (334, 27, 'Aspargessuppe (Toro)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (335, 27, 'Tomatsuppe (Toro)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (336, 27, 'Fruktsuppe (Toro)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (337, 27, 'Kjøttsuppe (Toro)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (338, 27, 'Bali Kyllinggryte (Toro)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (339, 27, 'Bolognese Gryte (Toro)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (340, 27, 'Meksikansk Gryte (Toro)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (341, 27, 'Italiensk Gryte (Toro)', 8, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (28, 'Frostvørur', '🧊', 28);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (28, 28, 'Frostvørur', '🧊', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (342, 28, 'Big One Pepperoni Pizza', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (343, 28, 'Big One Meat Lover Pizza', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (344, 28, 'Big One Classic Pizza', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (345, 28, 'Thai Cube Red Curry Chicken (Kohberg, 330g)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (346, 28, 'Chicken Nuggets (Fripozo, glutenfrí)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (347, 28, 'Chicken Nuggets Crispy (Fripozo, 750g)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (348, 28, 'Hot Wings (Fripozo, 750g)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (349, 28, 'Kyllinge Overlår (Rose, 1000g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (350, 28, 'Kyllinge Underlår (Rose)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (351, 28, 'Whole Frozen Chicken (Qualiko, 1000g)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (352, 28, 'Roasted Chicken Fillet Strips (200g)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (353, 28, 'Crunchy Chicken-Burger (Top Table, 1000g)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (354, 28, 'Chef Frites Crinkle Cut (McCain, 750g)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (355, 28, 'American Style Hamburg (25 x 100g)', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (356, 28, 'Middags Frikadeller (Rema 1000)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (357, 28, 'Middags Kødboller (Rema 1000, 500g)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (358, 28, 'Kød- og melboller (Maren Frost)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (359, 28, 'Melboller (Rema 1000, 600g)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (360, 28, 'Forårsruller (Daloon Classic, 8 stk.)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (361, 28, 'Wok Blanding (Rema 1000, 400g)', 20, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (362, 28, 'Suppeurter (Rema 1000, 600g)', 21, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (363, 28, 'Ris Blanding (Rema 1000, 500g)', 22, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (364, 28, 'Blomkåls Blanding (Rema 1000, 400g)', 23, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (365, 28, 'Broccoli Blanding (Rema 1000, 400g)', 24, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (366, 28, 'Frostbønnur', 25, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (367, 28, 'Classic Ispind (Rema 1000, 4 stk.)', 26, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (368, 28, 'Karamel Knas Pind (Rema 1000, 4 stk.)', 27, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (369, 28, 'Sport Limonadeis Mini (Rema 1000, 12 stk.)', 28, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (370, 28, 'Is Terninger (2kg)', 29, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (29, 'Sjogláta', '🍫', 29);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (29, 29, 'Sjogláta', '🍫', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (371, 29, 'Dairy Milk (Cadbury)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (372, 29, 'Crunchie (Cadbury)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (373, 29, 'Wispa (Cadbury)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (374, 29, 'Twirl (Cadbury)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (375, 29, 'Boost (Cadbury)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (376, 29, 'Snickers', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (377, 29, 'Mars', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (378, 29, 'Twix', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (379, 29, 'Milky Way', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (380, 29, 'KitKat (Nestlé)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (381, 29, 'Smarties (Nestlé)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (382, 29, 'Aero (Nestlé)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (383, 29, 'Lion (Nestlé)', 13, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (384, 29, 'Daim', 14, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (385, 29, 'Sport (Cloetta, 50g)', 15, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (386, 29, 'Kexchoklad (Cloetta)', 16, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (387, 29, 'Space (biscuit karamel)', 17, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (388, 29, 'Confitok Mørk (Carletti)', 18, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (389, 29, 'Lys Chipschips (Carletti, 21 stk.)', 19, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (390, 29, 'Makreludchocolade (Galle & Jessen, 216g)', 20, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (30, 'Snacks & Chips', '🍟', 30);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (30, 30, 'Snacks & Chips', '🍟', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (391, 30, 'Danske Franske Kartofler (Kims)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (392, 30, 'Sour Cream & Dild (Kims)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (393, 30, 'Cheeeese! Ostepops (Kims)', 3, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (394, 30, 'Mexican Fiesta (Kims)', 4, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (395, 30, 'Salt & Pepper (Kims)', 5, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (396, 30, 'Snack Chips Sour Cream & Onion (Kims)', 6, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (397, 30, 'Skruer (Kims)', 7, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (398, 30, 'Saltstænger (Rema 1000, 200g)', 8, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (399, 30, 'Mikroovn Popcorn med salt (Rema 1000, 3x100g)', 9, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (400, 30, 'Dipmix (Kims)', 10, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (401, 30, 'Dipmix Barbecue (Kims)', 11, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (402, 30, 'Sun Lolly Cola (8 stk.)', 12, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (403, 30, 'Sun Lolly (8 stk.)', 13, 1);
INSERT INTO categories (id, name, emoji, sort_order) VALUES (31, 'Djóramatur', '🐾', 31);
INSERT INTO products (id, category_id, name, emoji, type, sort_order, in_stock) VALUES (31, 31, 'Djóramatur', '🐾', 'expandable', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (404, 31, 'Hundemad med Kylling (Rema 1000, 300g)', 1, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (405, 31, 'Kattemad med Fisk & Rejer (Rema 1000, 100g)', 2, 1);
INSERT INTO sub_items (id, product_id, name, sort_order, in_stock) VALUES (406, 31, 'Katte Grus (Møler, 8L)', 3, 1);
